# Generated by Django 4.1 on 2023-11-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Starter", "Starter"),
                            ("Main Couse", "Main Course"),
                            ("Dessert", "Dessert"),
                        ],
                        max_length=80,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
