# Generated by Django 4.1 on 2023-11-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.CharField(
                choices=[
                    ("Starter", "Starter"),
                    ("Main Course", "Main Course"),
                    ("Dessert", "Dessert"),
                ],
                max_length=80,
            ),
        ),
    ]
