# Generated by Django 4.1 on 2023-11-22 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                        ]
                    ),
                ),
                ("date", models.DateField()),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("17:00", "5:00 PM"),
                            ("17:30", "5:30 PM"),
                            ("18:00", "6:00 PM"),
                            ("18:30", "6:30 PM"),
                            ("19:00", "7:00 PM"),
                            ("19:30", "7:30 PM"),
                            ("20:00", "8:00 PM"),
                            ("20:30", "8:30 PM"),
                            ("21:00", "9:00 PM"),
                            ("21:30", "9:30 PM"),
                            ("22:00", "10:00 PM"),
                        ],
                        max_length=5,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("allergy", models.TextField(blank=True, max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
