# Generated by Django 4.1 on 2023-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="number_of_guests",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="time",
            field=models.TimeField(max_length=8),
        ),
    ]
