# Generated by Django 4.1 on 2023-11-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="time",
        ),
        migrations.AddField(
            model_name="bookings",
            name="time_slot",
            field=models.IntegerField(
                choices=[
                    (1, "13:00 - 15:00"),
                    (2, "15:00 - 17:00"),
                    (3, "17:00 - 19:00"),
                    (4, "19:00 - 21:00"),
                    (5, "21:00 - 22:00"),
                    (6, "22:00 - 00:00"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="bookings",
            name="timestamp_booking_made",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="number_of_guests",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ]
            ),
        ),
    ]
