# Generated by Django 4.1 on 2023-11-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_alter_bookings_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="time",
            field=models.TimeField(
                choices=[
                    ("17:00", "17:00"),
                    ("17:30", "17:30"),
                    ("18:00", "18:00"),
                    ("18:30", "18:30"),
                    ("19:00", "19:00"),
                    ("19:30", "19:30"),
                    ("20:00", "20:00"),
                    ("20:30", "20:30"),
                    ("21:00", "21:00"),
                    ("21:30", "21:30"),
                    ("22:00", "22:00"),
                ]
            ),
        ),
    ]
