# Generated by Django 4.1 on 2023-11-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0014_alter_bookings_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="time",
            field=models.TimeField(
                choices=[
                    ("17:00:00", "17:00:00"),
                    ("17:30:00", "17:30:00"),
                    ("18:00:00", "18:00:00"),
                    ("18:30:00", "18:30:00"),
                    ("19:00:00", "19:00:00"),
                    ("19:30:00", "19:30:00"),
                    ("20:00:00", "20:00:00"),
                    ("20:30:00", "20:30:00"),
                    ("21:00:00", "21:00:00"),
                    ("21:30:00", "21:30:00"),
                    ("22:00:00", "22:00:00"),
                ],
                max_length=8,
            ),
        ),
    ]
