# Generated by Django 4.1 on 2023-11-27 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0021_alter_bookings_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="time",
            field=models.TimeField(
                choices=[
                    (datetime.time(17, 0), "17:00"),
                    (datetime.time(17, 30), "17:30"),
                    (datetime.time(18, 0), "18:00"),
                    (datetime.time(18, 30), "18:30"),
                    (datetime.time(19, 0), "19:00"),
                    (datetime.time(19, 30), "19:30"),
                    (datetime.time(20, 0), "20:00"),
                    (datetime.time(20, 30), "20:30"),
                    (datetime.time(21, 0), "21:00"),
                    (datetime.time(21, 30), "21:30"),
                    (datetime.time(22, 0), "22:00"),
                    (datetime.time(22, 30), "22:30"),
                    (datetime.time(23, 0), "23:00"),
                    (datetime.time(23, 30), "23:30"),
                    (datetime.time(0, 0), "00:00"),
                ]
            ),
        ),
    ]
