# Generated by Django 4.1 on 2023-11-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0024_alter_bookings_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="time",
        ),
        migrations.AddField(
            model_name="bookings",
            name="time_slot",
            field=models.IntegerField(
                choices=[
                    (1, "16:00 - 16:30"),
                    (2, "17:00 - 17:00"),
                    (3, "17:30 - 17:30"),
                    (4, "18:00 - 18:00"),
                    (5, "19:00 - 19:30"),
                    (6, "20:00 - 20:00"),
                    (7, "20:30 - 20:30"),
                    (8, "21:00 - 21:00"),
                    (9, "21:30 - 21:30"),
                    (10, "22:00 - 22:00"),
                    (11, "22:30 - 22:30"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="bookings",
            name="timestamp_booking_made",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
