# Generated by Django 4.1 on 2023-11-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0025_remove_bookings_time_bookings_time_slot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="time_slot",
            field=models.IntegerField(
                choices=[
                    (1, "13:00 - 15:00"),
                    (2, "15:00 - 17:00"),
                    (3, "17:00 - 19:00"),
                    (4, "19:00 - 21:00"),
                    (5, "21:00 - 22:00"),
                    (6, "22:00 - 00:00"),
                ],
                default=1,
            ),
        ),
    ]
